// src/components/DayDetail.svelte
<!-- src/components/DayDetail.svelte -->
<script>
  import ActivityItem from './ActivityItem.svelte';
  export let day;
</script>

<section id={day.id} class="day-section">
  <div class="container">
    <div class="day-header">
      <h2 class="day-title">{day.emoji} Day {day.dayNumber}: {day.title}</h2>
      <div class="day-date">{day.date}</div>
    </div>
    
    <img src={day.image.src} alt={day.image.alt} class="day-image">
    
    <div class="quote-box">
      "{day.quote.text}" - {day.quote.author}
    </div>
    
    <div class="daily-summary">
      <div class="summary-title">Day Summary</div>
      <p>{day.summary}</p>
      
      <div class="drive-info">
        <strong>Total Driving:</strong> ~{day.driving.total.distance.km} km ({day.driving.total.distance.miles} miles), {day.driving.total.time}
        <ul>
          {#each day.driving.segments as segment}
            <li>{segment.from} to {segment.to}: ~{segment.distance.km} km ({segment.distance.miles} miles), {segment.time}</li>
          {/each}
        </ul>
      </div>
    </div>
    
    <div class="map-container">
      {@html day.mapUrl}
    </div>
    
    <div class="day-schedule">
      <h3 class="section-heading">Daily Schedule</h3>
      <div class="activity-timeline">
        {#each day.schedule as item}
          <ActivityItem {item} />
        {/each}
      </div>
    </div>
    
    <!-- Highlights Section -->
    <div class="highlights-section">
      <h4>Key Highlights of the Day</h4>
      <ul class="highlights-list">
        {#each day.highlights as highlight, i}
          <li>
            {#if typeof highlight === 'string'}
              {highlight}
            {:else}
              {#if highlight.link}
                <a href={highlight.link} target="_blank" rel="noopener"><strong>{highlight.title}:</strong></a> {highlight.description}
              {:else}
                <strong>{highlight.title}:</strong> {highlight.description}
              {/if}
            {/if}
          </li>
        {/each}
      </ul>
    </div>
    
    <!-- Accommodations Section -->
    <div class="accommodations-section">
      <h4>Accommodations</h4>
      <div class="accommodations-details">
        <strong>{day.accommodation.name}</strong>
        <br>
        {day.accommodation.address}
        <br>
        Cost: {day.accommodation.cost}
        <br>
        {day.accommodation.roomType}
        {#if day.accommodation.notes}
          <br>
          Note: {day.accommodation.notes}
        {/if}
      </div>
    </div>
    
    <!-- Alternatives Section -->
    <div class="alternatives-section">
      <h4>Alternative Activities</h4>
      <ul class="alternatives-list">
        {#each day.alternatives as alt}
          <li>
            {#if alt.link}
              <a href={alt.link} target="_blank" rel="noopener"><strong>{alt.title}:</strong></a> {alt.description}
            {:else}
              <strong>{alt.title}:</strong> {alt.description}
            {/if}
            {#if alt.isGem}<span class="badge gem-badge">💎 Hidden Gem</span>{/if}
            {#if alt.isUserSelected}<span class="badge selected-badge">✓ Selected</span>{/if}
          </li>
        {/each}
      </ul>
    </div>
    
    <!-- Bad Weather Alternatives -->
    <div class="weather-section">
      <h4>Bad Weather Alternatives</h4>
      <ul class="weather-list">
        {#each day.badWeatherAlternatives as alt}
          <li>
            {#if alt.link}
              <a href={alt.link} target="_blank" rel="noopener"><strong>{alt.title}:</strong></a> {alt.description}
            {:else}
              <strong>{alt.title}:</strong> {alt.description}
            {/if}
          </li>
        {/each}
      </ul>
    </div>
    
    <!-- Hot Springs Section -->
    {#if day.hotSprings && day.hotSprings.length > 0}
      <div class="hotsprings-section">
        <h4><span class="hotspring-icon">♨️</span> Hot Springs</h4>
        <ul class="hotsprings-list">
          {#each day.hotSprings as spring}
            <li class={spring.isEveningRelaxation ? 'evening-relaxation' : ''}>
              {#if spring.link}
                <a href={spring.link} target="_blank" rel="noopener"><strong>{spring.name}:</strong></a> {spring.description}
              {:else}
                <strong>{spring.name}:</strong> {spring.description}
              {/if}
              <div class="hotspring-details">
                <span class="hotspring-location"><strong>Location:</strong> {spring.location}</span>
                <span class="hotspring-cost"><strong>Cost:</strong> {spring.cost}</span>
                {#if spring.isEveningRelaxation}
                  <span class="evening-badge">✨ Evening Relaxation</span>
                {/if}
              </div>
            </li>
          {/each}
        </ul>
      </div>
    {/if}
    
    <!-- Tips & Notes -->
    {#if day.tip}
      <div class="tip-box">{day.tip}</div>
    {/if}
    
    {#if day.notes}
      <div class="notes-container">
        <h4>Notes</h4>
        {#if typeof day.notes === 'string'}
          <p>{day.notes}</p>
        {:else if Array.isArray(day.notes) && day.notes.length > 0}
          <ul class="notes-list">
            {#each day.notes as note}
              <li>{note}</li>
            {/each}
          </ul>
        {/if}
      </div>
    {/if}
  </div>
</section>

<style>
  .section-heading {
    font-size: 1.4em;
    color: var(--primary-dark);
    margin-bottom: 20px;
    position: relative;
    padding-left: 20px;
  }

  .section-heading:before {
    content: '';
    position: absolute;
    left: 0;
    top: 50%;
    transform: translateY(-50%);
    width: 10px;
    height: 10px;
    background-color: var(--primary);
    border-radius: 50%;
  }
  
  .activity-timeline {
    position: relative;
    padding-left: 30px;
  }

  .activity-timeline:before {
    content: '';
    position: absolute;
    left: 5px;
    top: 0;
    height: 100%;
    width: 2px;
    background-color: var(--gray-light);
  }
  
  .badge {
    font-size: 0.75em;
    padding: 2px 6px;
    border-radius: 4px;
    margin-left: 8px;
    display: inline-flex;
    align-items: center;
    gap: 4px;
  }
  
  .gem-badge {
    background-color: var(--primary);
    color: white;
  }
  
  .selected-badge {
    background-color: var(--success);
    color: white;
  }
  
  .notes-container {
    padding: 20px;
    background-color: #f8f9fa;
    border-radius: 12px;
    margin: 25px 0;
    border-left: 3px solid var(--primary);
  }
  
  .notes-container h4 {
    margin-top: 0;
    margin-bottom: 15px;
    color: var(--primary-dark);
  }
  
  .notes-list {
    margin-top: 10px;
    margin-left: 20px;
    list-style-type: disc;
  }
  
  .notes-list li {
    margin-bottom: 8px;
  }
  
  /* Hot Springs Section Styles */
  .hotsprings-section {
    padding: 25px;
    background-color: #e9f7fb;
    border-radius: 12px;
    margin: 25px 0;
    border-left: 4px solid #17a2b8;
    position: relative;
    overflow: hidden;
  }
  
  .hotsprings-section:before {
    content: '';
    position: absolute;
    top: 0;
    right: 0;
    width: 120px;
    height: 120px;
    background: radial-gradient(circle, rgba(23, 162, 184, 0.15) 20%, rgba(23, 162, 184, 0) 70%);
    border-radius: 50%;
    z-index: 0;
  }
  
  .hotsprings-section h4 {
    display: flex;
    align-items: center;
    font-size: 1.3em;
    margin-bottom: 15px;
    color: #17a2b8;
  }
  
  .hotspring-icon {
    font-size: 1.2em;
    margin-right: 10px;
  }
  
  .hotsprings-list {
    list-style: none;
    padding: 0;
  }
  
  .hotsprings-list li {
    position: relative;
    padding: 15px;
    margin-bottom: 15px;
    background-color: white;
    border-radius: 8px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);
    transition: transform 0.2s ease, box-shadow 0.2s ease;
  }
  
  .hotsprings-list li:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  
  .hotsprings-list li.evening-relaxation {
    background: linear-gradient(to right, white, #f8f4ff);
    border-left: 3px solid #9c27b0;
  }
  
  .hotspring-details {
    display: flex;
    flex-wrap: wrap;
    gap: 15px;
    margin-top: 8px;
    font-size: 0.9em;
    color: #666;
  }
  
  .evening-badge {
    display: inline-block;
    background-color: #9c27b0;
    color: white;
    padding: 3px 8px;
    border-radius: 12px;
    font-size: 0.75em;
    margin-left: auto;
  }
  
  a {
    color: var(--primary);
    text-decoration: none;
    transition: color 0.2s ease;
  }
  
  a:hover {
    color: var(--primary-dark);
    text-decoration: underline;
  }
</style>

// components/DayDetail.tsx
import { DayData } from '../types';
import ActivityItem from './ActivityItem';
import Image from 'next/image';
import { memo } from 'react';

interface DayDetailProps {
  day: DayData;
}

// Custom map component that safely handles the iframe
const SafeMapEmbed = memo(({ mapUrl }: { mapUrl: string }) => {
  // Extract the actual URL from the iframe HTML string
  const getMapUrl = (iframeString: string) => {
    const srcMatch = iframeString.match(/src="([^"]+)"/);
    return srcMatch ? srcMatch[1] : '';
  };
  
  const actualMapUrl = getMapUrl(mapUrl);
  
  return (
    <div className="map-container">
      <iframe
        src={actualMapUrl}
        width="100%"
        height="450"
        style={{ border: 0, borderRadius: '10px' }}
        allowFullScreen
        loading="lazy"
        title="Day Map"
        aria-label="Interactive map for the day's route"
      />
    </div>
  );
});

SafeMapEmbed.displayName = 'SafeMapEmbed';

function DayDetail({ day }: DayDetailProps) {
  return (
    <section id={day.id} className="day-section">
      <div className="container">
        <div className="day-header">
          <h2 className="day-title">{day.emoji} Day {day.dayNumber}: {day.title}</h2>
          <div className="day-date">{day.date}</div>
        </div>
        
        {/* Using standard img tag since we're optimizing images externally 
            and we specified unoptimized: true in next.config.js */}
        <img 
          src={day.image.src} 
          alt={day.image.alt} 
          className="day-image"
          width={1200}
          height={600}
        />
        
        <blockquote className="quote-box">
          <p>"{day.quote.text}"</p>
          <footer>- {day.quote.author}</footer>
        </blockquote>
        
        <div className="daily-summary">
          <h3 className="summary-title">Day Summary</h3>
          <p>{day.summary}</p>
          
          <div className="drive-info">
            <strong>Total Driving:</strong> ~{day.driving.total.distance.km} km ({day.driving.total.distance.miles} miles), {day.driving.total.time}
            <ul>
              {day.driving.segments.map((segment, index) => (
                <li key={index}>
                  {segment.from} to {segment.to}: ~{segment.distance.km} km ({segment.distance.miles} miles), {segment.time}
                </li>
              ))}
            </ul>
          </div>
        </div>
        
        {/* Using a safe map component instead of dangerouslySetInnerHTML */}
        {day.mapUrl && (
          <SafeMapEmbed mapUrl={day.mapUrl} />
        )}
        
        <div className="day-schedule">
          <h3 className="section-heading">Daily Schedule</h3>
          <div className="activity-timeline">
            {day.schedule.map((item, index) => (
              <ActivityItem key={index} item={item} />
            ))}
          </div>
        </div>
        
        {/* Highlights Section */}
        <section className="highlights-section" aria-labelledby="highlights-heading">
          <h4 id="highlights-heading">Key Highlights of the Day</h4>
          <ul className="highlights-list">
            {day.highlights.map((highlight, index) => (
              <li key={index}>
                {typeof highlight === 'string' ? (
                  highlight
                ) : (
                  <>
                    {highlight.link ? (
                      <a href={highlight.link} target="_blank" rel="noopener noreferrer">
                        <strong>{highlight.title}:</strong>
                      </a>
                    ) : (
                      <strong>{highlight.title}:</strong>
                    )}
                    {' '}{highlight.description}
                  </>
                )}
              </li>
            ))}
          </ul>
        </section>
        
        {/* Accommodations Section */}
        <section className="accommodations-section" aria-labelledby="accommodations-heading">
          <h4 id="accommodations-heading">Accommodations</h4>
          <div className="accommodations-details">
            <strong>{day.accommodation.name}</strong>
            <address>
              {day.accommodation.address}
            </address>
            <p>
              <span className="label">Cost:</span> {day.accommodation.cost}<br />
              <span className="label">Room Type:</span> {day.accommodation.roomType}
              {day.accommodation.notes && (
                <>
                  <br />
                  <span className="label">Note:</span> {day.accommodation.notes}
                </>
              )}
            </p>
          </div>
        </section>
        
        {/* Alternatives Section */}
        <section className="alternatives-section" aria-labelledby="alternatives-heading">
          <h4 id="alternatives-heading">Alternative Activities</h4>
          <ul className="alternatives-list">
            {day.alternatives.map((alt, index) => (
              <li key={index}>
                {alt.link ? (
                  <a href={alt.link} target="_blank" rel="noopener noreferrer">
                    <strong>{alt.title}:</strong>
                  </a>
                ) : (
                  <strong>{alt.title}:</strong>
                )}
                {' '}{alt.description}
                {alt.isGem && <span className="badge gem-badge" aria-label="Hidden Gem">💎 Hidden Gem</span>}
                {alt.isUserSelected && <span className="badge selected-badge" aria-label="Selected Activity">✓ Selected</span>}
              </li>
            ))}
          </ul>
        </section>
        
        {/* Bad Weather Alternatives */}
        <section className="weather-section" aria-labelledby="weather-heading">
          <h4 id="weather-heading">Bad Weather Alternatives</h4>
          <ul className="weather-list">
            {day.badWeatherAlternatives.map((alt, index) => (
              <li key={index}>
                {alt.link ? (
                  <a href={alt.link} target="_blank" rel="noopener noreferrer">
                    <strong>{alt.title}:</strong>
                  </a>
                ) : (
                  <strong>{alt.title}:</strong>
                )}
                {' '}{alt.description}
              </li>
            ))}
          </ul>
        </section>
        
        {/* Hot Springs Section */}
        {day.hotSprings && day.hotSprings.length > 0 && (
          <section className="hotsprings-section" aria-labelledby="hotsprings-heading">
            <h4 id="hotsprings-heading"><span className="hotspring-icon" aria-hidden="true">♨️</span> Hot Springs</h4>
            <ul className="hotsprings-list">
              {day.hotSprings.map((spring, index) => (
                <li 
                  key={index} 
                  className={spring.isEveningRelaxation ? 'evening-relaxation' : ''}
                >
                  {spring.link ? (
                    <a href={spring.link} target="_blank" rel="noopener noreferrer">
                      <strong>{spring.name}:</strong>
                    </a>
                  ) : (
                    <strong>{spring.name}:</strong>
                  )}
                  {' '}{spring.description}
                  <div className="hotspring-details">
                    <span className="hotspring-location">
                      <strong>Location:</strong> {spring.location}
                    </span>
                    <span className="hotspring-cost">
                      <strong>Cost:</strong> {spring.cost}
                    </span>
                    {spring.isEveningRelaxation && (
                      <span className="evening-badge" aria-label="Evening Relaxation Option">✨ Evening Relaxation</span>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          </section>
        )}
        
        {/* Tips & Notes */}
        {day.tip && <aside className="tip-box" aria-label="Tip">{day.tip}</aside>}
        
        {day.notes && (
          <section className="notes-container" aria-labelledby="notes-heading">
            <h4 id="notes-heading">Notes</h4>
            {typeof day.notes === 'string' ? (
              <p>{day.notes}</p>
            ) : Array.isArray(day.notes) && day.notes.length > 0 ? (
              <ul className="notes-list">
                {day.notes.map((note, index) => (
                  <li key={index}>{note}</li>
                ))}
              </ul>
            ) : null}
          </section>
        )}
      </div>
    </section>
  );
}

export default memo(DayDetail);
