// src/components/SwipeNavigation.svelte
<!-- src/components/SwipeNavigation.svelte -->
<script>
  import { onMount, onDestroy } from 'svelte';
  
  // Props
  export let currentIndex = 0;
  export let totalItems = 0;
  export let onNavigate = (newIndex) => {};
  export let threshold = 100; // Minimum distance to trigger a swipe
  export let disabled = false;
  
  // State
  let touchStartX = 0;
  let touchEndX = 0;
  let isSwiping = false;
  let swipeOffset = 0;
  let element;
  
  // Handle touch start
  function handleTouchStart(e) {
    if (disabled) return;
    
    touchStartX = e.touches[0].clientX;
    isSwiping = true;
    swipeOffset = 0;
  }
  
  // Handle touch move
  function handleTouchMove(e) {
    if (!isSwiping || disabled) return;
    
    touchEndX = e.touches[0].clientX;
    swipeOffset = touchEndX - touchStartX;
    
    // Prevent scrolling while swiping horizontally
    if (Math.abs(swipeOffset) > 10) {
      e.preventDefault();
    }
  }
  
  // Handle touch end
  function handleTouchEnd() {
    if (!isSwiping || disabled) return;
    
    const swipeDistance = touchEndX - touchStartX;
    
    if (swipeDistance > threshold && currentIndex > 0) {
      // Swiped right - go to previous
      onNavigate(currentIndex - 1);
    } else if (swipeDistance < -threshold && currentIndex < totalItems - 1) {
      // Swiped left - go to next
      onNavigate(currentIndex + 1);
    }
    
    isSwiping = false;
    swipeOffset = 0;
  }
  
  // Set up and clean up event listeners
  onMount(() => {
    if (element) {
      element.addEventListener('touchstart', handleTouchStart, { passive: false });
      element.addEventListener('touchmove', handleTouchMove, { passive: false });
      element.addEventListener('touchend', handleTouchEnd, { passive: false });
    }
  });
  
  onDestroy(() => {
    if (element) {
      element.removeEventListener('touchstart', handleTouchStart);
      element.removeEventListener('touchmove', handleTouchMove);
      element.removeEventListener('touchend', handleTouchEnd);
    }
  });
</script>

<div class="swipe-container" bind:this={element}>
  <slot></slot>
  
  {#if isSwiping && Math.abs(swipeOffset) > 20}
    <div class="swipe-indicator {swipeOffset > 0 ? 'prev' : 'next'}" 
         style="opacity: {Math.min(Math.abs(swipeOffset) / threshold, 0.9)}">
      <div class="indicator-content">
        <span class="arrow">{swipeOffset > 0 ? '←' : '→'}</span>
        <span class="text">{swipeOffset > 0 ? 'Previous Day' : 'Next Day'}</span>
      </div>
    </div>
  {/if}
</div>

<style>
  .swipe-container {
    position: relative;
    width: 100%;
    height: 100%;
    overflow: hidden;
    touch-action: pan-y; /* Allow vertical scrolling */
  }
  
  .swipe-indicator {
    position: fixed;
    top: 0;
    bottom: 0;
    width: 80px;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    z-index: 900;
  }
  
  .swipe-indicator.prev {
    left: 0;
    border-top-right-radius: 8px;
    border-bottom-right-radius: 8px;
  }
  
  .swipe-indicator.next {
    right: 0;
    border-top-left-radius: 8px;
    border-bottom-left-radius: 8px;
  }
  
  .indicator-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
  }
  
  .arrow {
    font-size: 2rem;
    margin-bottom: 4px;
  }
  
  .text {
    font-size: 0.8rem;
    font-weight: 600;
  }
</style>

// components/SwipeNavigation.tsx
'use client';

import { useEffect, useState, useRef, ReactNode, useCallback, memo } from 'react';

interface SwipeNavigationProps {
  children: ReactNode[];
  currentIndex: number;
  onNavigate: (index: number) => void;
}

function SwipeNavigation({
  children,
  currentIndex,
  onNavigate
}: SwipeNavigationProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [touchStartX, setTouchStartX] = useState<number | null>(null);
  const [touchEndX, setTouchEndX] = useState<number | null>(null);
  const [swiping, setSwiping] = useState(false);
  
  // Memoize navigation functions to prevent unnecessary rerenders
  const navigateNext = useCallback(() => {
    if (currentIndex < children.length - 1) {
      onNavigate(currentIndex + 1);
    }
  }, [currentIndex, children.length, onNavigate]);
  
  const navigatePrevious = useCallback(() => {
    if (currentIndex > 0) {
      onNavigate(currentIndex - 1);
    }
  }, [currentIndex, onNavigate]);
  
  // Handle touch events for swipe detection
  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    setTouchStartX(e.targetTouches[0].clientX);
    setTouchEndX(e.targetTouches[0].clientX);
    setSwiping(true);
  }, []);
  
  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    if (!swiping) return;
    setTouchEndX(e.targetTouches[0].clientX);
  }, [swiping]);
  
  const handleTouchEnd = useCallback(() => {
    if (!touchStartX || !touchEndX) return;
    
    const distance = touchStartX - touchEndX;
    const isSignificantSwipe = Math.abs(distance) > 100;
    
    if (isSignificantSwipe) {
      if (distance > 0) {
        // Swiped left, go to next day
        navigateNext();
      } else {
        // Swiped right, go to previous day
        navigatePrevious();
      }
    }
    
    setSwiping(false);
    setTouchStartX(null);
    setTouchEndX(null);
  }, [touchStartX, touchEndX, navigateNext, navigatePrevious]);
  
  // Handle keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowLeft') {
        navigatePrevious();
      } else if (e.key === 'ArrowRight') {
        navigateNext();
      }
    };
    
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [navigatePrevious, navigateNext]);
  
  // Add navigation buttons for accessibility
  const hasPrevious = currentIndex > 0;
  const hasNext = currentIndex < children.length - 1;
  
  return (
    <div 
      ref={containerRef}
      className="swipe-container"
      onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove}
      onTouchEnd={handleTouchEnd}
      role="region"
      aria-label="Day navigation"
    >
      {children[currentIndex]}
      
      {/* Accessible navigation controls */}
      <div className="navigation-controls" aria-hidden="true">
        <button 
          onClick={navigatePrevious}
          disabled={!hasPrevious}
          className={`nav-button prev ${!hasPrevious ? 'disabled' : ''}`}
          aria-label="Previous day"
          tabIndex={hasPrevious ? 0 : -1}
        >
          ←
        </button>
        <button 
          onClick={navigateNext}
          disabled={!hasNext}
          className={`nav-button next ${!hasNext ? 'disabled' : ''}`}
          aria-label="Next day"
          tabIndex={hasNext ? 0 : -1}
        >
          →
        </button>
      </div>
      
      <p className="screen-reader-text">
        {hasPrevious ? "Swipe right or press left arrow key for previous day." : ""}
        {hasNext ? "Swipe left or press right arrow key for next day." : ""}
      </p>
      
      <style jsx>{`
        .swipe-container {
          touch-action: pan-y;
          position: relative;
          width: 100%;
          overflow: hidden;
        }
        
        .navigation-controls {
          display: none;
        }
        
        .screen-reader-text {
          position: absolute;
          width: 1px;
          height: 1px;
          padding: 0;
          margin: -1px;
          overflow: hidden;
          clip: rect(0, 0, 0, 0);
          white-space: nowrap;
          border-width: 0;
        }
        
        /* Only show buttons on non-touch devices */
        @media (pointer: fine) {
          .navigation-controls {
            display: flex;
            justify-content: space-between;
            position: absolute;
            top: 50%;
            left: 0;
            right: 0;
            transform: translateY(-50%);
            z-index: 10;
            padding: 0 20px;
          }
          
          .nav-button {
            background-color: rgba(0, 0, 0, 0.3);
            color: white;
            border: none;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            font-size: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            transition: background-color 0.2s;
          }
          
          .nav-button:hover:not(.disabled) {
            background-color: rgba(0, 0, 0, 0.5);
          }
          
          .nav-button.disabled {
            opacity: 0.3;
            cursor: not-allowed;
          }
        }
      `}</style>
    </div>
  );
}

export default memo(SwipeNavigation);
